### ISSUE TITLE
replace print with logging

### ISSUE THREAD

**Issue by MartinSunal** [FRINXio/FRINX-machine#109]
Python print does not provide enough granularity and therefore stdout is vorbose.

Replace print with python3 logging, especially in the wrapper which handles all workers' communication:
https://github.com/FRINXio/FRINX-machine/blob/master/microservices/netinfra_utils/workers/worker_wrapper.py

It should be possible to change logger log levels for stdout during a runtime.

**Comment by dhodovsk** [comment]
> It should be possible to change logger log levels for stdout during a runtime.

Are you suggesting some form of interprocess communication? If yes, which of these approaches do you like?

**Option 1**
Use SIGUSR signals. There are only two of them reserved for users, so you could only switch between logging.DEBUG and logging.INFO. The enabling could look like this:

Enable: `docker-compose -f docker-compose.bridge.yml exec micros kill -SIGUSR1 1`
Disable: `docker-compose -f docker-compose.bridge.yml exec micros kill -SIGUSR2 1` 

**Option 2**
Pass the desired logging level via file:
```
docker-compose -f docker-compose.bridge.yml exec micros bash -c 'echo ERROR > log_lvl.txt'
```
The script could then check the value of the file in a loop every x seconds or if even can be possible on-demand (with the use of one of the signals from option 1).

Do you have any other suggestions, maybe with the use of sockets, or any other of [these](https://docs.python.org/3/library/ipc.html).

**Comment by MartinSunal** [comment]
Code has been moved to uniflow-micros repository.
