### ISSUE TITLE
Frinx-machine is not starting up

### ISSUE THREAD

**Issue by mirackle-spb** [FRINXio/FRINX-machine#219]
Clean ubuntu 20.04 install. Single node. Docker networking configuration is incorrect. Some of services is always restarting and never came up. Logs gives error "no route to host" on database connection.

`302174873fc2   frinx/frinx-inventory-server:1.0.0                    "/run_inventory.sh"      11 seconds ago   Up 5 seconds (health: starting)    8000/tcp                                   fm_inventory.1.tvacdjh7ju7brk3553iiww4ol

538c10210286   frinx/uniflow-conductor-server:1.0.1                  "/bin/sh /app/startu…"   21 seconds ago   Up 14 seconds (health: starting)   8080/tcp, 8090/tcp                         fm_conductor-server.1.f8bdj733txmrumnhnjrq5wuzn

f482dd74ed6c   frinx/workflow-proxy:1.0.5                            "docker-entrypoint.s…"   31 seconds ago   Up 25 seconds (health: starting)   80/tcp, 8088/tcp                           fm_workflow-proxy.1.ix9d4y3h99uc2yobq0cwi6la5

91811dfe2e62   frinx/uniconfig:4.2.8                                 "/opt/uniconfig-frin…"   3 minutes ago    Up 3 minutes (health: starting)    8181/tcp, 8185/tcp                         fm_uniconfig-controller.1.r335f25w8ij9aebu7m0a3eq03
`

**Comment by gwieser1234** [comment]
Hi, feel free to contact us at "info@frinx.io" and we'll arrange a session to help you get up and running. Meanwhile, try out our demo setup here:
https://demo.frinx.io/
check out our demo workflows here:
https://docs.frinx.io/frinx-machine/use-cases/index.html
feel free to ask us any question.
Gerhard
