### ISSUE TITLE
UniConfig UI "Sync-from-network" with lighty uniconfig 4.2.3RC2 throws an error

### ISSUE THREAD

**Issue by gwieser1234** [FRINXio/FRINX-machine#22]
When I mount sample device IOS01 and I click on "sync-from-network" button in UniConfig UI I get an error.

<img width="922" alt="Screen Shot 2019-08-01 at 12 15 43 PM" src="https://user-images.githubusercontent.com/6385994/62285639-4c315780-b456-11e9-966e-0fdd170ea66a.png">

**Comment by TomasHodor** [comment]
FIXED https://github.com/FRINXio/frinx-uniconfig-ui/commit/e902d6b93bad6dadec497b73f3163a8976e17315
