### ISSUE TITLE
Mounting UC native with blacklist does not work

### ISSUE THREAD

**Issue by gwieser1234** [FRINXio/FRINX-machine#23]
mounting a device with uniconfig native with a blacklist does not work from the UI. I tried the following formats in the text box and both did not work. I tried to mount with postman and i worked.

openconfig-interfaces:interfaces,ietf-interfaces:interfaces,openconfig-vlan:vlans,openconfig-routing-policy:routing-policy

"openconfig-interfaces:interfaces","ietf-interfaces:interfaces","openconfig-vlan:vlans","openconfig-routing-policy:routing-policy"

**Comment by TomasHodor** [comment]
FIXED https://github.com/FRINXio/frinx-uniconfig-ui/pull/31
