### ISSUE TITLE
Question: UniFlow (workflow builder interface)

### ISSUE THREAD

**Issue by andra-sava** [FRINXio/FRINX-machine#236]
Hello, 

I am really interested in your solution but I have difficulties in finding the repository hosting the Uniflow interface solution, presented here: https://docs.frinx.io/frinx-uniflow/workflow-builder/workflow-builder.html
I suppose it should have been found at  https://github.com/FRINXio/fm-workflows  but the link is not working. 
Can you please provide a valid link?

Thank you!
Andra

**Comment by gwieser1234** [comment]
Andra, 
thank you for your interest. The best way to test the workflowbuilder UI is to run FRINX Machine. You can find the installation instructions here: https://github.com/FRINXio/FRINX-machine
Let us know what you would like to achieve and we will be happy to help you. 
Thanks,
g.

**Comment by Jozefiel** [comment]
Hi @andra-sava 

If you looking for a frontend code of workflow-builder, look on this link.
https://github.com/FRINXio/frinx-frontend/tree/main/packages/frinx-workflow-builder

fm-workflows contain demo workflows and workers, also sample topology for testing our Frinx Machine solution.
At this moment, the fm-workflows repo is not available, but you can test FM 1.8 with sources from this zip. 

[fm-workflows-1.7.zip](https://github.com/FRINXio/FRINX-machine/files/7661194/fm-workflows-1.7.zip)

Br
Jozef
