### ISSUE TITLE
Uniflow start fail

### ISSUE THREAD

**Issue by fireflyso** [FRINXio/FRINX-machine#240]
release: 1.8
os: Ubuntu 18.4
run startup.sh error info:
```
[INFO]: KrakenD image tag: 1.0.0
[INFO]: Uniflow swarm worker node id: t1qvyoyqfcnwsbqwwmfb2bx5z
service krakend: secret not found: frinx_krakend_tls_cert.pem
[ERROR]: Problem with starting Uniflow.
[ERROR]: If 'network frinx-machine not found!', wait a while and start Uniflow again.
```

check certificates file:
~/work/FRINX-machine-1.8# ls config/certificates/
frinx_krakend_tls_cert.pem  frinx_krakend_tls_key.pem  frinx_uniconfig_tls_cert.pem  frinx_uniconfig_tls_key.pem  frinx_uniconfig_X509.crt

frinx_krakend_tls_cert.pem file exist，so what's the problem

three is full log for run  startup.sh
```
[INFO]: Docker running in swarm mode
[INFO]: Selected resource configuration: ./config/prod_settings.txt
[INFO]: Deploying Uniflow, Uniconfig and Monitoring services
[INFO]: Monitoring swarm node id: t1qvyoyqfcnwsbqwwmfb2bx5z
Updating service fm_prometheus (id: z3g0hafkgm0gikn0gmxen25xr)
image prom/prometheus:v2.29.1 could not be accessed on a registry to record
its digest. Each node will access prom/prometheus:v2.29.1 independently,
possibly leading to different nodes running different
versions of the image.

Updating service fm_grafana (id: 6hlpmp044m5fpjxqw1yy53z4e)
image grafana/grafana:8.1.2 could not be accessed on a registry to record
its digest. Each node will access grafana/grafana:8.1.2 independently,
possibly leading to different nodes running different
versions of the image.

Updating service fm_swarm-node-info (id: hgd9ponn8v8l8mps8ujvv6r3a)
image prom/node-exporter:v1.2.2 could not be accessed on a registry to record
its digest. Each node will access prom/node-exporter:v1.2.2 independently,
possibly leading to different nodes running different
versions of the image.

Updating service fm_swarm-services-info (id: 4814yzz5u21cpuhctm3ab8hki)
image google/cadvisor:v0.33.0 could not be accessed on a registry to record
its digest. Each node will access google/cadvisor:v0.33.0 independently,
possibly leading to different nodes running different
versions of the image.

Updating service fm_loki (id: m76v4ugdb6w68w4d4cg7h22go)
image grafana/loki:2.2.1 could not be accessed on a registry to record
its digest. Each node will access grafana/loki:2.2.1 independently,
possibly leading to different nodes running different
versions of the image.

[INFO]: KrakenD image tag: 1.0.0
[INFO]: Uniflow swarm worker node id: t1qvyoyqfcnwsbqwwmfb2bx5z
service krakend: secret not found: frinx_krakend_tls_cert.pem
[ERROR]: Problem with starting Uniflow.
[ERROR]: If 'network frinx-machine not found!', wait a while and start Uniflow again.
```

**Comment by Jozefiel** [comment]
Hi @fireflyso 
Have you stored certificates in docker secrets?
Please check 
```
$ docker secret ls
hljmm9p1zb2pnpapiuagjm3wi   frinx_krakend_tls_cert.pem               21 hours ago   21 hours ago
jbnjucain2603ohiv3c1iibpw   frinx_krakend_tls_key.pem                21 hours ago   21 hours ago
hvqhn1ydjs57eqwrgkfkhwgjr   frinx_uniconfig_X509.crt                 21 hours ago   21 hours ago
mbr4lu2lbmpyk6480gba09slp   frinx_uniconfig_tls_cert.pem             21 hours ago   21 hours ago
qd8q25j8ofqw402xpqzev191u   frinx_uniconfig_tls_key.pem              21 hours ago   21 hours ago
```

These certificates are installed via ./install.sh script, try execute:  `./install.sh --skip --update-secrets` if secrets missing.

Jozef

**Comment by fireflyso** [comment]
>

**Comment by fireflyso** [comment]
> Hi @fireflyso Have you stored certificates in docker secrets? Please check
> 
> ```
> $ docker secret ls
> hljmm9p1zb2pnpapiuagjm3wi   frinx_krakend_tls_cert.pem               21 hours ago   21 hours ago
> jbnjucain2603ohiv3c1iibpw   frinx_krakend_tls_key.pem                21 hours ago   21 hours ago
> hvqhn1ydjs57eqwrgkfkhwgjr   frinx_uniconfig_X509.crt                 21 hours ago   21 hours ago
> mbr4lu2lbmpyk6480gba09slp   frinx_uniconfig_tls_cert.pem             21 hours ago   21 hours ago
> qd8q25j8ofqw402xpqzev191u   frinx_uniconfig_tls_key.pem              21 hours ago   21 hours ago
> ```
> 
> These certificates are installed via ./install.sh script, try execute: `./install.sh --skip --update-secrets` if secrets missing.
> 
> Jozef

Thanks, servers start success!
I have tried `./install.sh --skip --update-secrets`, but not work, it's a bug for install.sh script?
Finally solved the problem by manually importing the certificate

**Comment by Jozefiel** [comment]
Thanks for the information @fireflyso. 
You had probably Frinx Machine running. 
It's not possible to change docker secrets on a fly.

BR 
Jozef
