### ISSUE TITLE
Elastic Search always fails

### ISSUE THREAD

**Issue by MohZaibAli** [FRINXio/FRINX-machine#304]
![Services](https://user-images.githubusercontent.com/68590303/216051685-92ebdcdc-c744-45e2-9666-a4a55e55a89b.JPG)
![Containers](https://user-images.githubusercontent.com/68590303/216051754-d45b8f28-85a1-49dd-9e14-5198556b1624.JPG)
![ElasticsearchLogs](https://user-images.githubusercontent.com/68590303/216051768-5f89d189-fde9-48f2-b8cd-7a02ff58dba3.JPG)

**Comment by Jozefiel** [comment]
Hi @MohZaibAli 

Please try to increase health-check start period for elk
https://github.com/FRINXio/FRINX-machine/blob/master/composefiles/swarm-workflow-manager.yml#L184

or increase resources:

for prod setup:
https://github.com/FRINXio/FRINX-machine/blob/master/config/prod_settings.txt#L60-L62
for dev setup:
https://github.com/FRINXio/FRINX-machine/blob/master/config/dev_settings.txt#L60-L62
